name: deepl
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.6
  - pip=22.2.2
  - numpy==1.23.3
  - autopep8==1.6.0
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.3
  - conda-forge::pytorch-lightning==1.7.7
  - matplotlib==3.5.3
  - seaborn==0.12.0


